server:
  port: 9999
spring:
  application:
    name: saint
#  datasource:
#    bas:
#      jdbc-url: jdbc:oracle:thin:@10.0.13.44:1521/ERP.aonong.com.cn
#      username: bas
#      password: Y4dsc#996Liby
#      driver-class-name: oracle.jdbc.OracleDriver
#    rl:
#      jdbc-url: jdbc:oracle:thin:@10.0.13.44:1521/ERP.aonong.com.cn
#      username: rl
#      password: Yh3yxyz#40Liby
#      driver-class-name: oracle.jdbc.OracleDriver
#    hikari:
#      connection-test-query: SELECT 1 FROM DUAL
#      connection-timeout: 30000
#      maximum-pool-size: 5
#      max-lifetime: 1800000
#      minimum-idle: 5
  aop:
    auto: true